# -*- coding: utf-8 -*-

"""Universal parameter name constants for NavaTools scripts."""

# ==============================================================================
# Bluebeam Map Parameters  (_UMI_BBM_)
# Shared parameters sourced from Bluebeam CSV data
# ==============================================================================

# fmt: off
# autopep8: off
BBM_AUTHOR                                          = '_UMI_BBM_Author'
BBM_CEILING                                         = '_UMI_BBM_Ceiling'
BBM_CFM_EA                                          = '_UMI_BBM_CFMEA'
BBM_CFM_SA                                          = '_UMI_BBM_CFMSA'
BBM_CLASS                                           = '_UMI_BBM_Class'
BBM_COLOR                                           = '_UMI_BBM_Color'
BBM_COMMENTS                                        = '_UMI_BBM_Comments'
BBM_DAMPER                                          = '_UMI_BBM_Damper'
BBM_DEVICE                                          = '_UMI_BBM_Device'
BBM_DUTY                                            = '_UMI_BBM_Duty'
BBM_FACE                                            = '_UMI_BBM_Face'
BBM_FAN                                             = '_UMI_BBM_Fan'
BBM_GPM                                             = '_UMI_BBM_GPM'
BBM_HAND                                            = '_UMI_BBM_Hand'
BBM_HP                                              = '_UMI_BBM_HP'
BBM_K                                               = '_UMI_BBM_K'
BBM_KW                                              = '_UMI_BBM_KW'
BBM_LABEL                                           = '_UMI_BBM_Label'
BBM_LAYER                                           = '_UMI_BBM_Layer'
BBM_MAKE                                            = '_UMI_BBM_Make'
BBM_MATERIAL                                        = '_UMI_BBM_Material'
BBM_MODEL                                           = '_UMI_BBM_Model'
BBM_MOUNT                                           = '_UMI_BBM_Mount'
BBM_NECK                                            = '_UMI_BBM_Neck'
BBM_NOTES                                           = '_UMI_BBM_Notes'
BBM_NUMBER                                          = '_UMI_BBM_Number'
BBM_PAGE_LABEL                                      = '_UMI_BBM_PageLabel'
BBM_PAINT                                           = '_UMI_BBM_Paint'
BBM_PHASE                                           = '_UMI_BBM_Phase'
BBM_QTY                                             = '_UMI_BBM_Qty'
BBM_SECTION                                         = '_UMI_BBM_Section'
BBM_SIZE                                            = '_UMI_BBM_Size'
BBM_SLEEVE                                          = '_UMI_BBM_Sleeve'
BBM_SLOT                                            = '_UMI_BBM_Slot'
BBM_SPACE                                           = '_UMI_BBM_Space'
BBM_STATUS                                          = '_UMI_BBM_Status'
BBM_SUBCLASS                                        = '_UMI_BBM_Subclass'
BBM_SUBJECT                                         = '_UMI_BBM_Subject'
BBM_SYSTEM                                          = '_UMI_BBM_System'
BBM_TRADE                                           = '_UMI_BBM_Trade'
BBM_TYPE                                            = '_UMI_BBM_Type'
BBM_UNIT                                            = '_UMI_BBM_Unit'
BBM_VAV                                             = '_UMI_BBM_VAV'
BBM_VPH                                             = '_UMI_BBM_VPH'
# fmt: on
# autopep8: on

# ==============================================================================
# PyRevit Computed Parameters  (_UMI_PYT_)
# Parameters written by NavaTools scripts
# ==============================================================================

# fmt: off
# autopep8: off
PYT_ASPECT_RATIO                                    = '_UMI_PYT_AspectRatio'
PYT_CFM                                             = '_UMI_PYT_CFM'
PYT_HEIGHT_PAD                                      = '_UMI_PYT_HeightPad'
PYT_LABEL                                           = '_UMI_PYT_Label'
PYT_NOTE_0                                          = '_UMI_PYT_Note0'
PYT_NOTE_1                                          = '_UMI_PYT_Note1'
PYT_NOTE_2                                          = '_UMI_PYT_Note2'
PYT_NOTE_3                                          = '_UMI_PYT_Note3'
PYT_NOTE_4                                          = '_UMI_PYT_Note4'
PYT_NUMBER                                          = '_UMI_PYT_Number'
PYT_NUMBER_FABRICATION                              = "_UMI_PYT_NumberFabrication"
PYT_NUMBER_SLEEVE                                   = "_UMI_PYT_NumberSleeve"
PYT_OFFSET_BOTTOM                                   = '_UMI_PYT_OffsetBottom'
PYT_OFFSET_CENTER_H                                 = '_UMI_PYT_OffsetCenterH'
PYT_OFFSET_CENTER_V                                 = '_UMI_PYT_OffsetCenterV'
PYT_OFFSET_LEFT                                     = '_UMI_PYT_OffsetLeft'
PYT_OFFSET_RIGHT                                    = '_UMI_PYT_OffsetRight'
PYT_OFFSET_TOP                                      = '_UMI_PYT_OffsetTop'
PYT_OFFSET_VALUE                                    = '_UMI_PYT_OffsetValue'
PYT_SKIP_NUMBER                                     = '_UMI_PYT_SkipNumber'
PYT_SKIP_TAG                                        = '_UMI_PYT_SkipTag'
PYT_SLEEVE                                          = '_UMI_PYT_Sleeve'
PYT_SLEEVE_OPENING                                  = '_UMI_PYT_SleeveOpening'
PYT_SLEEVE_VALUE                                    = '_UMI_PYT_SleeveValue'
PYT_WEIGHT_RUN                                      = '_UMI_PYT_WeightRun'
PYT_WEIGHT_SUPPORT                                  = '_UMI_PYT_WeightSupport'
# fmt: on
# autopep8: on

# ==============================================================================
# Legacy UMI / Script Parameters
# Existing project parameters currently found in fabrication models
# ==============================================================================

# fmt: off
# autopep8: off
LEGACY_NUMBER                                       = '_#'
LEGACY_MAKE                                         = '_make'
LEGACY_MODEL                                        = '_model'
LEGACY_MOUNT                                        = '_mount'
LEGACY_OFFSET                                       = '_offset'
LEGACY_OFFSET_BOTTOM                                = '_offset_bottom'
LEGACY_OFFSET_CENTER_H                              = '_offset_center_h'
LEGACY_OFFSET_CENTER_V                              = '_offset_center_v'
LEGACY_OFFSET_LEFT                                  = '_offset_left'
LEGACY_OFFSET_RIGHT                                 = '_offset_right'
LEGACY_OFFSET_TOP                                   = '_offset_top'
LEGACY_POSITION                                     = '_position'
LEGACY_RUN_WEIGHT                                   = '_run_weight'
LEGACY_SKIP                                         = '_skip'
LEGACY_SLEEVE                                       = '_sleeve'
LEGACY_TYPE                                         = '_type'
LEGACY_V_PH                                         = '_v_ph'
LEGACY_VALUE_K                                      = '_value_k'
# fmt: on
# autopep8: on

# ==============================================================================
# Revit / Fabrication Parameters
# Named parameters from element dump used by ductwork workflows
# ==============================================================================

# fmt: off
# autopep8: off
RVT_AIRFLOW                                         = 'Airflow'
RVT_ALIAS                                           = 'Alias'
RVT_ANGLE                                           = 'Angle'
RVT_ASSEMBLY_CODE                                   = 'Assembly Code'
RVT_ASSEMBLY_DESCRIPTION                            = 'Assembly Description'
RVT_BOTTOM_ELEVATION                                = 'Bottom Elevation'
RVT_BOTTOM_ELEVATION_WITH_INSULATION                = 'Bottom Elevation with Insulation'
RVT_BOUGHT_OUT                                      = 'Bought Out'
RVT_CATEGORY                                        = 'Category'
RVT_CLEARANCE_ZONE                                  = 'Clearance Zone'
RVT_COMMENTS                                        = 'Comments'
RVT_COST                                            = 'Cost'
RVT_CRITICAL_PATH                                   = 'Critical Path'
RVT_CUT_TYPE                                        = 'Cut Type'
RVT_DESIGN_OPTION                                   = 'Design Option'
RVT_DESCRIPTION                                     = 'Description'
RVT_DOUBLE_WALL_MATERIAL_ABBREVIATION               = 'Double Wall Material Abbreviation'
RVT_DOUBLE_WALL_MATERIAL_AREA                       = 'Double Wall Material Area'
RVT_ELEVATION_BASE                                  = 'Elevation Base'
RVT_END_MIDDLE_ELEVATION                            = 'End Middle Elevation'
RVT_EXPORT_TO_IFC                                   = 'Export to IFC'
RVT_EXPORT_TO_IFC_AS                                = 'Export to IFC As'
RVT_EXPORT_TYPE_TO_IFC                              = 'Export Type to IFC'
RVT_EXPORT_TYPE_TO_IFC_AS                           = 'Export Type to IFC As'
RVT_FABRICATION_FITTING_DESCRIPTION                 = 'Fabrication Fitting Description'
RVT_FABRICATION_NOTES                               = 'Fabrication Notes'
RVT_FABRICATION_SERVICE                             = 'Fabrication Service'
RVT_FABRICATION_SERVICE_ABBREVIATION                = 'Fabrication Service Abbreviation'
RVT_FABRICATION_SERVICE_NAME                        = 'Fabrication Service Name'
RVT_FAMILY                                          = 'Family'
RVT_FAMILY_AND_TYPE                                 = 'Family and Type'
RVT_FAMILY_NAME                                     = 'Family Name'
RVT_FLOW                                            = 'Flow'
RVT_FREE_SIZE                                       = 'Free Size'
RVT_FRICTION                                        = 'Friction'
RVT_FRICTION_FACTOR                                 = 'Friction Factor'
RVT_HYDRAULIC_DIAMETER                              = 'Hydraulic Diameter'
RVT_IFC_PREDEFINED_TYPE                             = 'IFC Predefined Type'
RVT_IFC_GUID                                        = 'IfcGUID'
RVT_IMAGE                                           = 'Image'
RVT_INSIDE_DIAMETER                                 = 'Inside Diameter'
RVT_INSTALL_TYPE                                    = 'Install Type'
RVT_INSULATION_ABBREVIATION                         = 'Insulation Abbreviation'
RVT_INSULATION_AREA                                 = 'Insulation Area'
RVT_INSULATION_SPECIFICATION                        = 'Insulation Specification'
RVT_INSULATION_SPECIFICATION_ABBREVIATION           = 'Insulation Specification Abbreviation'
RVT_ITEM_NUMBER                                     = 'Item Number'
RVT_KEYNOTE                                         = 'Keynote'
RVT_LEADER_ARROWHEAD                                = 'Leader Arrowhead'
RVT_LEADER_LINE                                     = 'Leader Line'
RVT_LEADER_TYPE                                     = 'Leader Type'
RVT_LENGTH                                          = 'Length'
RVT_LENGTH_OPTION                                   = 'Length Option'
RVT_LINING_AREA                                     = 'Lining Area'
RVT_LOWER_END_BOTTOM_ELEVATION                      = 'Lower End Bottom Elevation'
RVT_LOWER_END_BOTTOM_OF_INSULATION_ELEVATION        = 'Lower End Bottom of Insulation Elevation'
RVT_LOWER_END_CENTERLINE_ELEVATION                  = 'Lower End Centerline Elevation'
RVT_LOWER_END_INVERT_ELEVATION                      = 'Lower End Invert Elevation'
RVT_LOWER_END_OBVERT_ELEVATION                      = 'Lower End Obvert Elevation'
RVT_LOWER_END_TOP_ELEVATION                         = 'Lower End Top Elevation'
RVT_LOWER_END_TOP_OF_INSULATION_ELEVATION           = 'Lower End Top of Insulation Elevation'
RVT_MAIN_PRIMARY_DEPTH                              = 'Main Primary Depth'
RVT_MAIN_PRIMARY_DIAMETER                           = 'Main Primary Diameter'
RVT_MAIN_PRIMARY_WIDTH                              = 'Main Primary Width'
RVT_MAIN_SECONDARY_DEPTH                            = 'Main Secondary Depth'
RVT_MAIN_SECONDARY_DIAMETER                         = 'Main Secondary Diameter'
RVT_MAIN_SECONDARY_WIDTH                            = 'Main Secondary Width'
RVT_MAIN_SECONDARY_WIDTH_OPTION                     = 'Main Secondary Width Option'
RVT_MANUFACTURER                                    = 'Manufacturer'
RVT_MARK                                            = 'Mark'
RVT_MATERIAL_ABBREVIATION                           = 'Material Abbreviation'
RVT_MATERIAL_GAUGE                                  = 'Material Gauge'
RVT_MIDDLE_ELEVATION                                = 'Middle Elevation'
RVT_MODEL                                           = 'Model'
RVT_MORE_PARAMETERS                                 = 'More Parameters'
RVT_OEM                                             = 'OEM'
RVT_ORIENTATION                                     = 'Orientation'
RVT_OUTSIDE_DIAMETER                                = 'Outside Diameter'
RVT_OVERALL_SIZE                                    = 'Overall Size'
RVT_PART_MATERIAL                                   = 'Part Material'
RVT_PART_MATERIAL_THICKNESS                         = 'Part Material Thickness'
RVT_PART_PATTERN_NUMBER                             = 'Part Pattern Number'
RVT_PART_SHEET_METAL_AREA                           = 'Part Sheet Metal Area'
RVT_PHASE_CREATED                                   = 'Phase Created'
RVT_PHASE_DEMOLISHED                                = 'Phase Demolished'
RVT_PIPE_INVERT_ELEVATION                           = 'Pipe Invert Elevation'
RVT_PRESSURE_DROP                                   = 'Pressure Drop'
RVT_PRODUCT_CODE                                    = 'Product Code'
RVT_PRODUCT_FINISH_DESCRIPTION                      = 'Product Finish Description'
RVT_PRODUCT_LONG_DESCRIPTION                        = 'Product Long Description'
RVT_PRODUCT_MATERIAL_DESCRIPTION                    = 'Product Material Description'
RVT_PRODUCT_NAME                                    = 'Product Name'
RVT_PRODUCT_RANGE                                   = 'Product Range'
RVT_PRODUCT_SHORT_DESCRIPTION                       = 'Product Short Description'
RVT_PRODUCT_SIZE_DESCRIPTION                        = 'Product Size Description'
RVT_PRODUCT_SPECIFICATION_DESCRIPTION               = 'Product Specification Description'
RVT_REFERENCE_LEVEL                                 = 'Reference Level'
RVT_RELATIVE_ROUGHNESS                              = 'Relative Roughness'
RVT_REYNOLDS_NUMBER                                 = 'Reynolds number'
RVT_ROUGHNESS                                       = 'Roughness'
RVT_SECTION                                         = 'Section'
RVT_SIZE                                            = 'Size'
RVT_SIZE_OF_CONNECTOR_END                           = 'Size of Connector End'
RVT_SIZE_OF_PRIMARY_BRANCH_END                      = 'Size of Primary Branch End'
RVT_SIZE_OF_PRIMARY_END                             = 'Size of Primary End'
RVT_SIZE_OF_SECONDARY_END                           = 'Size of Secondary End'
RVT_SLOPE                                           = 'Slope'
RVT_SPECIFICATION                                   = 'Specification'
RVT_SPECIFICATION_ABBREVIATION                      = 'Specification Abbreviation'
RVT_SPOT_BOTTOM_ELEVATION                           = 'Spot Bottom Elevation'
RVT_SPOT_BOTTOM_OF_INSULATION_ELEVATION             = 'Spot Bottom of Insulation Elevation'
RVT_SPOT_CENTERLINE_ELEVATION                       = 'Spot Centerline Elevation'
RVT_SPOT_TOP_ELEVATION                              = 'Spot Top Elevation'
RVT_SPOT_TOP_OF_INSULATION_ELEVATION                = 'Spot Top of Insulation Elevation'
RVT_START_MIDDLE_ELEVATION                          = 'Start Middle Elevation'
RVT_SU_SD_FROM_BOTTOM                               = 'SU/SD from Bottom'
RVT_SU_SD_FROM_TOP                                  = 'SU/SD from Top'
RVT_SYSTEM_ABBREVIATION                             = 'System Abbreviation'
RVT_TOP_ELEVATION                                   = 'Top Elevation'
RVT_TOP_ELEVATION_WITH_INSULATION                   = 'Top Elevation with Insulation'
RVT_TYPE                                            = 'Type'
RVT_TYPE_COMMENTS                                   = 'Type Comments'
RVT_TYPE_ID                                         = 'Type Id'
RVT_TYPE_IFC_PREDEFINED_TYPE                        = 'Type IFC Predefined Type'
RVT_TYPE_IFC_GUID                                   = 'Type IfcGUID'
RVT_TYPE_IMAGE                                      = 'Type Image'
RVT_TYPE_MARK                                       = 'Type Mark'
RVT_TYPE_NAME                                       = 'Type Name'
RVT_UPPER_END_BOTTOM_ELEVATION                      = 'Upper End Bottom Elevation'
RVT_UPPER_END_BOTTOM_OF_INSULATION_ELEVATION        = 'Upper End Bottom of Insulation Elevation'
RVT_UPPER_END_CENTERLINE_ELEVATION                  = 'Upper End Centerline Elevation'
RVT_UPPER_END_INVERT_ELEVATION                      = 'Upper End Invert Elevation'
RVT_UPPER_END_OBVERT_ELEVATION                      = 'Upper End Obvert Elevation'
RVT_UPPER_END_TOP_ELEVATION                         = 'Upper End Top Elevation'
RVT_UPPER_END_TOP_OF_INSULATION_ELEVATION           = 'Upper End Top of Insulation Elevation'
RVT_URL                                             = 'URL'
RVT_VELOCITY                                        = 'Velocity'
RVT_VELOCITY_PRESSURE                               = 'Velocity Pressure'
RVT_VENDOR                                          = 'Vendor'
RVT_VENDOR_CODE                                     = 'Vendor Code'
RVT_WALL_THICKNESS                                  = 'Wall Thickness'
RVT_WEIGHT                                          = 'Weight'
# fmt: on
# autopep8: on

# ==============================================================================
# Naviate DBS Parameters
# ==============================================================================

# fmt: off
# autopep8: off
NDBS_APPR                                           = 'NaviateDBS__Appr'
NDBS_REV                                            = 'NaviateDBS__Rev'
NDBS_CHK                                            = 'NaviateDBS__Chk'
NDBS_ALIAS                                          = 'NaviateDBS_Alias'
NDBS_BOTTOM_OF_PART_ELEVATION                       = 'NaviateDBS_BottomOfPartElevation'
NDBS_CENTERLINE_LENGTH                              = 'NaviateDBS_CenterlineLength'
NDBS_CONNECTOR0_END_CONDITION                       = 'NaviateDBS_Connector0_EndCondition'
NDBS_CONNECTOR1_END_CONDITION                       = 'NaviateDBS_Connector1_EndCondition'
NDBS_CONNECTOR2_END_CONDITION                       = 'NaviateDBS_Connector2_EndCondition'
NDBS_CONNECTOR_MANAGER                              = 'NaviateDBS_ConnectorManager'
NDBS_CUT_TYPE                                       = 'NaviateDBS_CutType'
NDBS_D_ANGLE                                        = 'NaviateDBS_D_Angle'
NDBS_D_BOTTOM_EXTENSION                             = 'NaviateDBS_D_Bottom Extension'
NDBS_D_BTM_WIDTH                                    = 'NaviateDBS_D_Btm Width'
NDBS_D_COLLAR                                       = 'NaviateDBS_D_Collar'
NDBS_D_CORNER_RADIUS                                = 'NaviateDBS_D_Corner Radius'
NDBS_D_DEPTH                                        = 'NaviateDBS_D_Depth'
NDBS_D_DEPTH_IN                                     = 'NaviateDBS_D_Depth In'
NDBS_D_DEPTH_OUT                                    = 'NaviateDBS_D_Depth Out'
NDBS_D_DIAMETER                                     = 'NaviateDBS_D_Diameter'
NDBS_D_EXTENSION                                    = 'NaviateDBS_D_Extension'
NDBS_D_EXTENSION_IN                                 = 'NaviateDBS_D_Extension In'
NDBS_D_EXTENSION_OUT                                = 'NaviateDBS_D_Extension Out'
NDBS_D_INNER_RADIUS                                 = 'NaviateDBS_D_Inner Radius'
NDBS_D_LEFT_COLLAR                                  = 'NaviateDBS_D_Left Collar'
NDBS_D_LEFT_EXTENSION                               = 'NaviateDBS_D_Left Extension'
NDBS_D_LEFT_RADIUS                                  = 'NaviateDBS_D_Left Radius'
NDBS_D_LEFT_WIDTH                                   = 'NaviateDBS_D_Left Width'
NDBS_D_LENGTH                                       = 'NaviateDBS_D_Length'
NDBS_D_OFFSET                                       = 'NaviateDBS_D_Offset'
NDBS_D_OFFSET_DEPTH                                 = 'NaviateDBS_D_Offset Depth'
NDBS_D_OFFSET_WIDTH                                 = 'NaviateDBS_D_Offset Width'
NDBS_D_OFFSET_DEPTH_HYPHEN                          = 'NaviateDBS_D_Offset-Depth'
NDBS_D_OFFSET_WIDTH_HYPHEN                          = 'NaviateDBS_D_Offset-Width'
NDBS_D_RIGHT_COLLAR                                 = 'NaviateDBS_D_Right Collar'
NDBS_D_RIGHT_EXTENSION                              = 'NaviateDBS_D_Right Extension'
NDBS_D_RIGHT_RADIUS                                 = 'NaviateDBS_D_Right Radius'
NDBS_D_RIGHT_WIDTH                                  = 'NaviateDBS_D_Right Width'
NDBS_D_SLOPE_ANGLE                                  = 'NaviateDBS_D_Slope Angle'
NDBS_D_SPLITTER_DISTANCE                            = 'NaviateDBS_D_Splitter Distance'
NDBS_D_TOP_EXTENSION                                = 'NaviateDBS_D_Top Extension'
NDBS_D_TOP_WIDTH                                    = 'NaviateDBS_D_Top Width'
NDBS_D_WIDTH                                        = 'NaviateDBS_D_Width'
NDBS_D_WIDTH_IN                                     = 'NaviateDBS_D_Width In'
NDBS_D_WIDTH_OUT                                    = 'NaviateDBS_D_Width Out'
NDBS_DOMAIN_TYPE                                    = 'NaviateDBS_DomainType'
NDBS_DOUBLE_WALL_MATERIAL                           = 'NaviateDBS_DoubleWallMaterial'
NDBS_DOUBLE_WALL_MATERIAL_AREA                      = 'NaviateDBS_DoubleWallMaterialArea'
NDBS_DOUBLE_WALL_MATERIAL_THICKNESS                 = 'NaviateDBS_DoubleWallMaterialThickness'
NDBS_DUCT_OVERALL_SIZE_H_W                          = 'NaviateDBS_DuctOverallSize_H-W'
NDBS_DUCT_OVERALL_SIZE_W_H                          = 'NaviateDBS_DuctOverallSize_W-H'
NDBS_FAMILY                                         = 'NaviateDBS_Family'
NDBS_FREE_SIZE                                      = 'NaviateDBS_FreeSize'
NDBS_GEOMETRY_CHECKSUM                              = 'NaviateDBS_GeometryChecksum'
NDBS_HANGER_ROD_KIT                                 = 'NaviateDBS_HangerRodKit'
NDBS_HAS_DOUBLE_WALL                                = 'NaviateDBS_HasDoubleWall'
NDBS_HAS_INSULATION                                 = 'NaviateDBS_HasInsulation'
NDBS_HAS_LINING                                     = 'NaviateDBS_HasLining'
NDBS_INSULATION_AREA                                = 'NaviateDBS_InsulationArea'
NDBS_INSULATION_SPECIFICATION                       = 'NaviateDBS_InsulationSpecification'
NDBS_INSULATION_THICKNESS                           = 'NaviateDBS_InsulationThickness'
NDBS_INSULATION_TYPE                                = 'NaviateDBS_InsulationType'
NDBS_IS_BOUGHT_OUT                                  = 'NaviateDBS_IsBoughtOut'
NDBS_ITEM_CUSTOM_ID                                 = 'NaviateDBS_ItemCustomId'
NDBS_ITEM_NUMBER                                    = 'NaviateDBS_ItemNumber'
NDBS_LEVEL_OFFSET                                   = 'NaviateDBS_LevelOffset'
NDBS_LINING_AREA                                    = 'NaviateDBS_LiningArea'
NDBS_LINING_THICKNESS                               = 'NaviateDBS_LiningThickness'
NDBS_LINING_TYPE                                    = 'NaviateDBS_LiningType'
NDBS_MATERIAL                                       = 'NaviateDBS_Material'
NDBS_MATERIAL_GAUGE                                 = 'NaviateDBS_MaterialGauge'
NDBS_MATERIAL_THICKNESS                             = 'NaviateDBS_MaterialThickness'
NDBS_NOTES                                          = 'NaviateDBS_Notes'
NDBS_ORIGIN                                         = 'NaviateDBS_Origin'
NDBS_OVERALL_SIZE                                   = 'NaviateDBS_OverallSize'
NDBS_PART_GUID                                      = 'NaviateDBS_PartGuid'
NDBS_PART_STATUS                                    = 'NaviateDBS_PartStatus'
NDBS_PRODUCT_CODE                                   = 'NaviateDBS_ProductCode'
NDBS_PRODUCT_DATA_RANGE                             = 'NaviateDBS_ProductDataRange'
NDBS_PRODUCT_FINISH_DESCRIPTION                     = 'NaviateDBS_ProductFinishDescription'
NDBS_PRODUCT_INSTALL_TYPE                           = 'NaviateDBS_ProductInstallType'
NDBS_PRODUCT_LIST_ENTRY                             = 'NaviateDBS_ProductListEntry'
NDBS_PRODUCT_LONG_DESCRIPTION                       = 'NaviateDBS_ProductLongDescription'
NDBS_PRODUCT_MATERIAL_DESCRIPTION                   = 'NaviateDBS_ProductMaterialDescription'
NDBS_PRODUCT_NAME                                   = 'NaviateDBS_ProductName'
NDBS_PRODUCT_ORIGINAL_EQUIPMENT_MANUFACTURE         = 'NaviateDBS_ProductOriginalEquipmentManufacture'
NDBS_PRODUCT_SHORT_DESCRIPTION                      = 'NaviateDBS_ProductShortDescription'
NDBS_PRODUCT_SIZE_DESCRIPTION                       = 'NaviateDBS_ProductSizeDescription'
NDBS_PRODUCT_SPECIFICATION_DESCRIPTION              = 'NaviateDBS_ProductSpecificationDescription'
NDBS_SERVICE_ABBREVIATION                           = 'NaviateDBS_ServiceAbbreviation'
NDBS_SERVICE_ID                                     = 'NaviateDBS_ServiceId'
NDBS_SERVICE_NAME                                   = 'NaviateDBS_ServiceName'
NDBS_SERVICE_TYPE                                   = 'NaviateDBS_ServiceType'
NDBS_SHEET_METAL_AREA                               = 'NaviateDBS_SheetMetalArea'
NDBS_SIZE                                           = 'NaviateDBS_Size'
NDBS_SLOPE                                          = 'NaviateDBS_Slope'
NDBS_SPECIFICATION                                  = 'NaviateDBS_Specification'
NDBS_SPOOL_NAME                                     = 'NaviateDBS_SpoolName'
NDBS_TOP_OF_PART_ELEVATION                          = 'NaviateDBS_TopOfPartElevation'
NDBS_VALIDATION_STATUS                              = 'NaviateDBS_ValidationStatus'
NDBS_VENDOR                                         = 'NaviateDBS_Vendor'
NDBS_VENDOR_CODE                                    = 'NaviateDBS_VendorCode'
NDBS_WEIGHT                                         = 'NaviateDBS_Weight'
# fmt: on
# autopep8: on
